[default]
DEBUG = true
TITLE = "NomeDoPrograma"

EXTENSIONS = [
    "src.blueprints.api"
]

[testing]
SQLALCHEMY_DATABASE_URI = 'sqlite:///testing.db'

[production]
SQLALCHEMY_DATABASE_URI = 'sqlite:///production.db'
